# Generated by Django 3.0.10 on 2022-07-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='has_max_pessanger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='bookingdetail',
            table='booking_detail',
        ),
        migrations.AlterModelTable(
            name='pessanger',
            table='pessanger',
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('arrive_time', models.TimeField()),
                ('flight_duration_m', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='plane.City')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.Flight')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.Meal')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='plane.City')),
            ],
            options={
                'db_table': 'departure',
            },
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plane.Ticket'),
            preserve_default=False,
        ),
    ]
