# Generated by Django 3.0.10 on 2022-07-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20220721_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plane.AgeGroup'),
            preserve_default=False,
        ),
    ]
