# Generated by Django 3.0.10 on 2022-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0003_auto_20220721_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
