# Generated by Django 3.0.10 on 2022-07-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_auto_20220721_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plane.BookingDetail'),
            preserve_default=False,
        ),
    ]
