# Generated by Django 3.0.10 on 2022-07-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_auto_20220721_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='base_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='is_reserverable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
