# Generated by Django 3.0.10 on 2022-07-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0005_auto_20220721_2240'),
        ('plane', '0005_auto_20220722_1211'),
    ]

    operations = [
    ]
