# Generated by Django 3.0.10 on 2022-07-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0007_flight_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plane.Departure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PessangerCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('expiry_date', models.DateField()),
                ('pessanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.Pessanger')),
            ],
            options={
                'db_table': 'pessanger_credit',
            },
        ),
    ]
