# Generated by Django 3.0.10 on 2022-07-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0008_auto_20220722_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight',
        ),
    ]
