# Generated by Django 3.0.10 on 2022-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0009_remove_booking_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='departure_id',
            new_name='departure',
        ),
    ]
