# Generated by Django 3.0.10 on 2022-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0012_auto_20220722_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='airline',
            field=models.ManyToManyField(to='plane.Airline'),
        ),
    ]
